### ISSUE TITLE
vencord.ts filename causing error

### ISSUE THREAD

**Issue by throwaway2444** [KaydaFox/vencord-buttplugio#2]
Was getting the following error:  [ERROR] Could not resolve "./userplugins/vencord-buttplugio"

After looking at vencord plugin docs it looked like trouble with the vencord.ts filename, renaming it to index.ts solved my issue

**Comment by TheFlyingFoool** [comment]
resolved from 53fc8bc49dbff24b0e988bfe9138cecfe5044790
